name: efficient_ransac
channels:
   - conda-forge
   - defaults
dependencies:
  - python=3.10
  - pcl=1.14.1
  - clang-format=19.1.7
  - pip
  - pip:
    - pytest
    - pre-commit
    - numpy
    - nanobind
    - scikit-learn
    - -e .
