success_probability_threshold: 0.99
num_candidates: 100
num_point_candidates: 3
num_inliers_min: 100
max_num_shapes: 3
use_localized_sampling: true

thresholds:
  distance: 0.2
  normal: 1.5

bitmap_cell_size: 0.1
